apiVersion: v1
kind: Service
metadata:
  namespace: simple-inventory-app
  labels:
    app: backend-app
  name: backend-service
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: backend-app
  type: ClusterIP
