auth:
  username: postgres
  database: postgres
  existingSecret: postgres-credentials
primary:
  persistence:
    storageClass: nfs-csi
    accessModes:
      - "ReadWriteOnce"
    size: 1Gi
resources:
  requests:
    memory: 768Mi
    cpu: 250m
  limits:
    memory: 1Gi
    cpu: 500m