apiVersion: v1
kind: Service
metadata:
  namespace: simple-inventory-app
  labels:
    app: frontend-app
  name: frontend-service
spec:
  ports:
    - name: http
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: frontend-app
  type: ClusterIP
